spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Dheeraj@99
  application:
    name: product-service

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

#dataconfig:
#  url: jdbc:mysql://localhost:3306/test
#  username: root
#  password: Dheeraj@99